# Generated by Django 4.0.4 on 2022-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commission',
            field=models.FloatField(),
        ),
    ]
