# Generated by Django 4.0.4 on 2022-05-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sale_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlist',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.sale'),
        ),
    ]
